# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "os/root";
    fsType = "zfs";
  };

  fileSystems."/boot1" = {
    device = "/dev/disk/by-uuid/B521-E7CE";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"

      "nofail"
    ];
  };

  fileSystems."/boot2" = {
    device = "/dev/disk/by-uuid/6054-F72D";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"

      "nofail"
    ];
  };

  fileSystems."/mnt/Data/Backup" = {
    device = "data/backup";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Deluge" = {
    device = "data/deluge";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Monitoring" = {
    device = "data/monitoring";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Movies" = {
    device = "data/movies";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Series" = {
    device = "data/series";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Sync" = {
    device = "data/sync";
    fsType = "zfs";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
