{
  imports = [
    ./documentation.nix
    ./fwupd.nix
    ./git.nix
    ./hardening.nix
    ./i18n.nix
    ./kernel-latest.nix
    ./kernel-panic.nix
    ./keyboard.nix
    ./nftables.nix
    ./nix.nix
    ./nvd.nix
    ./shell.nix
    ./sudo-rs.nix
    ./systemd.nix
    ./tailscale.nix
    ./tmp-management.nix
    ./util.nix
  ];
}
