{
  imports = [
    ./displaylink.nix
    ./fwupd.nix
    ./git.nix
    ./gnome
    ./i18n.nix
    ./keyboard.nix
    ./nautilus.nix
    ./nftables.nix
    ./nix.nix
    ./nvd.nix
    ./printing.nix
    ./shell.nix
    ./tmp-management.nix
    ./trash-management.nix
    ./util.nix
  ];
}
