# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a345a75c-1c7c-486d-8b77-8eefd8a7ce89";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7892-8EC8";
    fsType = "vfat";
  };

  fileSystems."/mnt/Data" = {
    device = "data";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Backup" = {
    device = "data/backup";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Snapshots" = {
    device = "data/snapshots";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Sync" = {
    device = "data/sync";
    fsType = "zfs";
  };

  swapDevices = [ ];

  hardware.video.hidpi.enable = lib.mkDefault true;
}
