# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/783771e2-3491-4e6d-9e89-724917587836";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/605A-094C";
    fsType = "vfat";
  };

  fileSystems."/mnt/Data/Backup" = {
    device = "data/backup";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Deluge" = {
    device = "data/deluge";
    fsType = "zfs";
  };

  fileSystems."/mnt/Data/Snapshots" = {
    device = "data/snapshots";
    fsType = "zfs";
  };

  swapDevices = [ ];
}
