# https://esphome.io

# AirGradient ONE Indoor Monitor Kit Version 9

# Sensors:
#   - ESP32-C3-MINI
#   - SenseAir S8 CO2 sensor
#   - Plantower PMS5003 PM sensor
#   - Sensirion SGP41 TVOC/NOx Sensor (not in the picture)
#   - Sensirion SHT40 Temperature/Humidity Sensor

# Adapted from https://github.com/MallocArray/airgradient_esphome/tree/2.0.1

substitutions:
  name: airgradient-one
  friendly_name: AirGradient ONE
  name_add_mac_suffix: "false" # Must have quotes around value
  config_version: 1.0.0

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local

  ap:
    ssid: airgradient-84fce60259c0
    password: cleanair

# web_server:
#   port: 80
#   enable_private_network_access: false
#   include_internal: true
#   ota: false

dashboard_import:
  package_import_url: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/_config.yaml
  import_full_config: false

packages:
  board: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/board.yaml

  config_button: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/config_button.yaml
  diagnostic: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/diagnostic.yaml
  display_sh1106: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/display_sh1106.yaml
  hardware_watchdog: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/hardware_watchdog.yaml
  led_co2: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/led_co2.yaml
  led: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/led.yaml
  sensor_plantower_pms5003: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/sensor_plantower_pms5003.yaml
  sensor_senseair_s8: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/sensor_senseair_s8.yaml
  sensor_sensirion_sgp41: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/sensor_sensirion_sgp41.yaml
  sensor_sensirion_sht40: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/sensor_sensirion_sht40.yaml
  sensor_uptime: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/sensor_uptime.yaml
  sensor_wifi: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/sensor_wifi.yaml
  switch_safe_mode: github://rhoriguchi/nixos-setup/configuration/devices/headless/server/home-assistant/esphome/airgradient-one/switch_safe_mode.yaml
