esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: ${name_add_mac_suffix}

  project:
    name: rhoriguchi.airgradient
    version: ${config_version}

  min_version: 2023.12.0

esp32:
  board: esp32-c3-devkitm-1

logger:
  baud_rate: 0
  logs:
    component: ERROR

captive_portal:

uart:
  - id: senseair_s8_uart
    rx_pin: GPIO0
    tx_pin: GPIO1
    baud_rate: 9600

  - id: pms5003_uart
    rx_pin: GPIO20
    tx_pin: GPIO21
    baud_rate: 9600

i2c:
  sda: GPIO7
  scl: GPIO6
  frequency: 400kHz

button:
  - platform: factory_reset
    disabled_by_default: true
    name: "Factory Reset ESP"
    id: factory_reset_all
