font:
  - file: "gfonts://Open Sans"
    id: open_sans_14
    size: 14
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'
  - file: "gfonts://Open Sans"
    id: open_sans_9
    size: 9
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'
  - file: "gfonts://Open Sans"
    id: open_sans_20
    size: 20
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    id: oled_display
    address: 0x3C
    # Formatting reference: https://www.tutorialspoint.com/c_standard_library/c_function_printf.htm
    pages:
      - id: blank
        lambda: ''
      - id: summary
        lambda: |-
          it.printf(0, 0, id(open_sans_14), "%.1f°C", id(temp).state);
          it.printf(128, 0, id(open_sans_14), TextAlign::TOP_RIGHT, "%.1f%%", id(humidity).state);
          it.line(0,17,128,17);
          it.printf(0,19, id(open_sans_9), "CO2");
          it.printf(0,27, id(open_sans_20), "%.0f", id(co2).state);
          it.printf(0,52, id(open_sans_9), "ppm");
          it.line(50,19,50,64);
          it.printf(54, 19, id(open_sans_9), "PM2.5");
          it.printf(54, 27, id(open_sans_20), "%.0f", id(pm_2_5).state);
          it.printf(54, 52, id(open_sans_9), "µg/m³");
          it.line(100,19,100,64);
          it.printf(104,18, id(open_sans_9), "TVOC");
          it.printf(104,29, id(open_sans_9), "%.0f", id(voc).state);
          it.printf(104,41, id(open_sans_9), "NOx");
          it.printf(104,52, id(open_sans_9), "%.0f", id(nox).state);

    on_page_change:
      - to: blank
        then:
          - if:
              condition:
                  lambda: 'return id(display_contrast).state == 0;'
              then:
                - display.page.show: blank
              else:
                - display.page.show: summary
      - to: summary
        then:
          - if:
              condition:
                  lambda: 'return id(display_contrast).state == 0;'
              then:
                - display.page.show: blank
              else:
                - display.page.show: summary

number:
  - platform: template
    name: "Display Contrast %"
    icon: "mdi:lightbulb"
    id: display_contrast
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 100
    optimistic: true
    restore_value: true
    mode: slider
    on_value:
      then:
        - display.page.show: !lambda |-
            if (id(display_contrast).state == 0) {
              id(oled_display).set_contrast(0.0);
              return blank;
            } else {
              id(oled_display).set_contrast(id(display_contrast).state / 100.0);
              return summary;
            }
