interval:
  - interval: 1 min
    then:
      - if:
          condition:
            light.is_on: led_strip
          then:
            - if:
                condition:
                  lambda: 'return id(co2).state < 800;'
                then:
                  - light.turn_on:
                      id: led_strip
                      brightness: !lambda 'return id(led_brightness).state / 100.0;'
                      red: 0%
                      green: 100%
                      blue: 0%
            - if:
                condition:
                  lambda: 'return id(co2).state >= 800 && id(co2).state < 1000;'
                then:
                  - light.turn_on:
                      id: led_strip
                      brightness: !lambda 'return id(led_brightness).state / 100.0;'
                      red: 100%
                      green: 100%
                      blue: 0%
            - if:
                condition:
                  lambda: 'return id(co2).state >= 1000 && id(co2).state < 1500;'
                then:
                  - light.turn_on:
                      id: led_strip
                      brightness: !lambda 'return id(led_brightness).state / 100.0;'
                      red: 100%
                      green: 70%
                      blue: 0%
            - if:
                condition:
                  lambda: 'return id(co2).state >= 1500 && id(co2).state < 2000;'
                then:
                  - light.turn_on:
                      id: led_strip
                      brightness: !lambda 'return id(led_brightness).state / 100.0;'
                      red: 100%
                      green: 0%
                      blue: 0%
            - if:
                condition:
                  lambda: 'return id(co2).state >= 2000 && id(co2).state < 3000;'
                then:
                  - light.turn_on:
                      id: led_strip
                      brightness: !lambda 'return id(led_brightness).state / 100.0;'
                      red: 60%
                      green: 0%
                      blue: 60%
            - if:
                condition:
                  lambda: 'return id(co2).state >= 3000 && id(co2).state < 10000;'
                then:
                  - light.turn_on:
                      id: led_strip
                      brightness: !lambda 'return id(led_brightness).state / 100.0;'
                      red: 40%
                      green: 0%
                      blue: 0%
