sensor:
  - platform: sgp4x
    voc:
      name: "VOC Index"
      id: voc
    nox:
      name: "NOx Index"
      id: nox
    compensation:
      temperature_source: temp
      humidity_source: humidity
