{
 "title": "Network",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instanceName", "query": "XXLPitu-Router" },
   { "name": "externalInterface", "query": "eth4" },
   { "name": "internalInterface", "query": "eth3" },
   { "name": "wireguardInterface", "query": "wg-management" }
  ]
 },
 "panels": [
  { "title": "Ping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{exported_instance=\"$instanceName\", dimension=\"avg\", chart=~\"ping_dns\\\\..+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{exported_instance=\"$instanceName\", dimension=\"avg\", chart=~\"ping_internet\\\\..+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WireGuard",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{exported_instance=\"$instanceName\", dimension=\"avg\", chart=~\"ping_wireguard\\\\..+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{exported_instance=\"$instanceName\", dimension=\"avg\", chart=~\"ping_dns\\\\..+\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{exported_instance=\"$instanceName\", dimension=\"avg\", chart=~\"ping_internet\\\\..+\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "WireGuard",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{exported_instance=\"$instanceName\", dimension=\"avg\", chart=~\"ping_wireguard\\\\..+\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total: $externalInterface (External)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(sum_over_time(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", device=\"$externalInterface\"}[$__rate_interval]) / 8), \"dimension\", \"Up\", \"dimension\", \"received\"), \"dimension\", \"Down\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Total: $internalInterface (Internal)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(sum_over_time(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", device=\"$internalInterface\"}[$__rate_interval]) / 8), \"dimension\", \"Down\", \"dimension\", \"received\"), \"dimension\", \"Up\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Total: $wireguardInterface (WireGuard)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(sum_over_time(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", device=\"$wireguardInterface\"}[$__rate_interval]) / 8), \"dimension\", \"Down\", \"dimension\", \"received\"), \"dimension\", \"Up\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $externalInterface (External)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", device=\"$externalInterface\"}), \"dimension\", \"Up\", \"dimension\", \"received\"), \"dimension\", \"Down\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $internalInterface (Internal)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", device=\"$internalInterface\"}), \"dimension\", \"Down\", \"dimension\", \"received\"), \"dimension\", \"Up\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $wireguardInterface (WireGuard)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", device=\"$wireguardInterface\"}), \"dimension\", \"Down\", \"dimension\", \"received\"), \"dimension\", \"Up\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $externalInterface (External)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", device=\"$externalInterface\"}), \"dimension\", \"Up\", \"dimension\", \"received\"), \"dimension\", \"Down\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $internalInterface (Internal)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", device=\"$internalInterface\"}), \"dimension\", \"Up\", \"dimension\", \"received\"), \"dimension\", \"Down\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $wireguardInterface (WireGuard)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", device=\"$wireguardInterface\"}), \"dimension\", \"Down\", \"dimension\", \"received\"), \"dimension\", \"Up\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $internalInterface (Internal)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "sort(label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{exported_instance=\"$instanceName\", family=~\"${internalInterface}\\\\.\\\\d+\"}), \"dimension\", \"Down\", \"dimension\", \"received\"), \"dimension\", \"Up\", \"dimension\", \"sent\"))",
     "legendFormat": "{{dimension}} {{family}}"
    }
   ]
  },
  { "title": "DHCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Leases",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "netdata_prometheus_Kea_kea_dhcp4_addresses_assigned_total_assigned_average{exported_instance=\"$instanceName\", pool!=\"[none]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "netdata_prometheus_Kea_kea_dhcp4_addresses_assigned_total_assigned_average{exported_instance=\"$instanceName\", pool!=\"[none]\"}",
     "legendFormat": "{{subnet}}"
    }
   ]
  }
 ]
}