{
 "title": "Network",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "query": "XXLPitu-Urahara" },
   { "name": "externalInterface", "query": "eth4" },
   { "name": "internalInterface", "query": "eth3" }
  ]
 },
 "panels": [
  { "title": "Ping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{hostname=\"$hostname\", netdata_dimension=\"avg\", netdata_chart=~\"ping_dns\\\\..+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{hostname=\"$hostname\", netdata_dimension=\"avg\", netdata_chart=~\"ping_internet\\\\..+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{hostname=\"$hostname\", netdata_dimension=\"avg\", netdata_chart=~\"ping_dns\\\\..+\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "netdata_ping_host_rtt_milliseconds_average{hostname=\"$hostname\", netdata_dimension=\"avg\", netdata_chart=~\"ping_internet\\\\..+\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total: $externalInterface (External)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(abs(sum_over_time(netdata_net_net_kilobits_persec_average{hostname=\"$hostname\", device=\"$externalInterface\"}[$__rate_interval]) / 8), \"netdata_dimension\", \"Down\", \"netdata_dimension\", \"received\"), \"netdata_dimension\", \"Up\", \"netdata_dimension\", \"sent\")",
     "legendFormat": "{{netdata_dimension}}"
    }
   ]
  },
  {
   "title": "Total: $internalInterface (Internal)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(abs(sum_over_time(netdata_net_net_kilobits_persec_average{hostname=\"$hostname\", device=\"$internalInterface\"}[$__rate_interval]) / 8), \"netdata_dimension\", \"Down\", \"netdata_dimension\", \"received\"), \"netdata_dimension\", \"Up\", \"netdata_dimension\", \"sent\")",
     "legendFormat": "{{netdata_dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $externalInterface (External)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{hostname=\"$hostname\", device=\"$externalInterface\"}), \"netdata_dimension\", \"Down\", \"netdata_dimension\", \"received\"), \"netdata_dimension\", \"Up\", \"netdata_dimension\", \"sent\")",
     "legendFormat": "{{netdata_dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $internalInterface (Internal)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{hostname=\"$hostname\", device=\"$internalInterface\"}), \"netdata_dimension\", \"Down\", \"netdata_dimension\", \"received\"), \"netdata_dimension\", \"Up\", \"netdata_dimension\", \"sent\")",
     "legendFormat": "{{netdata_dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $externalInterface (External)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{hostname=\"$hostname\", device=\"$externalInterface\"}), \"netdata_dimension\", \"Down\", \"netdata_dimension\", \"received\"), \"netdata_dimension\", \"Up\", \"netdata_dimension\", \"sent\")",
     "legendFormat": "{{netdata_dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $internalInterface (Internal)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{hostname=\"$hostname\", device=\"$internalInterface\"}), \"netdata_dimension\", \"Up\", \"netdata_dimension\", \"received\"), \"netdata_dimension\", \"Down\", \"netdata_dimension\", \"sent\")",
     "legendFormat": "{{netdata_dimension}}"
    }
   ]
  },
  {
   "title": "Bandwith: $internalInterface (Internal)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(abs(netdata_net_net_kilobits_persec_average{hostname=\"$hostname\", netdata_family=~\"${internalInterface}\\\\.\\\\d+\"}), \"netdata_dimension\", \"Up\", \"netdata_dimension\", \"received\"), \"netdata_dimension\", \"Down\", \"netdata_dimension\", \"sent\")",
     "legendFormat": "{{netdata_dimension}} {{netdata_family}}"
    }
   ]
  },
  { "title": "DHCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Leases",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "netdata_prometheus_Kea_kea_dhcp4_addresses_assigned_total_assigned_average{hostname=\"$hostname\", pool!=\"[none]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 40 },
   "targets": [
    {
     "expr": "netdata_prometheus_Kea_kea_dhcp4_addresses_assigned_total_assigned_average{hostname=\"$hostname\", pool!=\"[none]\"}",
     "legendFormat": "{{subnet}}"
    }
   ]
  }
 ]
}